version: '3.0'
services:
    api:
        container_name: financial-manager_api
        hostname: financial-manager_api
        build: api/
        ports:
            - '8080:8080'
        restart: unless-stopped
        depends_on:
            - postgres
    postgres:
        image: 'postgres:15.1'
        container_name: 'fm_postgres'
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-root}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-12345}
            - POSTGRES_DB=${POSTGRES_DB:-fm}
            - PGDATA=/tmp
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        volumes:
            - ./db/postgres.sql:/docker-entrypoint-initdb.d/db.sql
            - ./db/volumes/postgres:/var/lib/postgresql/data
        restart: unless-stopped
