version: '3.0'
services:
    postgres:
        image: 'postgres:15.1'
        container_name: 'fm_postgres'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/tmp
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - ./db/postgres.sql:/docker-entrypoint-initdb.d/db.sql
            - ./db/volumes/postgres:/var/lib/postgresql/data
        restart: unless-stopped
